### ISSUE TITLE
Project status update?

### ISSUE THREAD

**Issue by joehorsnell** [SchemaPlus/schema_plus_foreign_keys#16]
Hi,

Just seeing if this project is still active and accepting PRs?

We use various `schema_plus*` gems in our Rails 4.2 apps, but are looking at upgrading to Rails 5.2, which isn't currently supported.

I can see there is PR #15 for Rails 5.2 support, but that just changes the gemspec. Would you be open to a PR for Rails 5.2 support?

Thanks!

Joe.

**Comment by ronen** [comment]
Hi -- I would absolutely be open to a PR for Rails 5.2 support!  

As I've said in other issues around the `schema_plus*` gems, unfortunately I don't currently use Rails in any of my day jobs, and just don't have enough free time to do any real development on it.  I'd be very psyched to have other active collaborators.

All that said, FYI since the time when #15 was submitted, schema_plus_core has been upgraded to support Rails 5.2; so this gem is now a lot closer than it was!

A thing to consider also is that over time Rails has been providing increasing support for foreign keys (A big change from the old days when Rails was officially opposed to the notion!  Which was actually the primary reason the first ancestor of this gem was written).  I haven't used Rails 5.2 myself, so I don't know whether some/all/none of the features of this gem are now natively supported in Rails.   If there are features of this gem that are now in rails but with different syntax, then the proper thing to do would be to continue to accept schema_plus syntax but with deprecation warnings in favor of the rails form (this has happened in the past; see the [deprecations when Rails 4.2 came out](https://github.com/SchemaPlus/schema_plus#deprecations)).

**Comment by joehorsnell** [comment]
Hi @ronen - thanks for the response and apologies for the delay in getting back to you.

Totally understand the situation you're in! When we get round to upgrading to Rails 5.2 we'll look at submitting a PR.

The main benefit (as I see it) of this gem vs the support that Rails has started to add is that it's automatic. As you note, Rails has added [`add_foreign_key`](https://edgeguides.rubyonrails.org/active_record_migrations.html#foreign-keys) to the migrations DSL, but it seems almost grudging support as you still need to remember to explicitly call it in your migrations.

The [official Rails advice](https://edgeguides.rubyonrails.org/active_record_migrations.html#active-record-and-referential-integrity) on RI is still to do it in application code, which to me is just plain wrong. Whilst I am a huge fan of Rails (it's our main web framework here at Bamboo) I strongly disagree on that advice - aside from being hugely inefficient to do "RI" in application code (compared to the DB) it's also _not_ RI, since it can't actually provide any guarantees. It's basically trivial to circumvent accidentally/intentionally through SQL updates and to expect to be able to manage _all_ updates to your data through Ruby/Rails once you start having a meaningful volume of data in your application (ie not use SQL) is just naive and totally artificially limiting (IMO).

Anyway, we'll get back to you, can't promise when, but hopefully in the next few months.

**Comment by joehorsnell** [comment]
To be fair, I was mistaken about the level of support provided by Rails.

It seems that since [this commit](https://github.com/rails/rails/commit/d2f837ee51d0f857e8fca33f96161c83a6a85f36) back in Feb 2015 (which has be in Rails 4.x since 4.2.1) and was a back port of various additions to that look to have been in Rails 5 since the first release, it's been possible to provide a `foreign_key: true` option to both `create_table` and `change_table`, which generates the required FK definition. So whilst not the default, still pretty convenient.

**Comment by garyfoster** [comment]
Hi @joehorsnell are you close to a PR for this? I could try to help if needed or if you are stuck on something. It's a bit low level for me but could try. I could at least test it if you're at that point.

**Comment by garyfoster** [comment]
I may try [this](https://alexpeattie.com/blog/stop-forgetting-foreign-key-indexes-in-rails-post-migration-script) as a short term and less elegant substitute.

**Comment by garyfoster** [comment]
or [this](https://github.com/gregnavis/active_record_doctor)

**Comment by joehorsnell** [comment]
Hi @garyfoster, our Rails 5.2 upgrade has been bumped by various other priorities, so this issue became less of a priority for us.

When we do come to upgrade though, we will probably consider whether just to use the built-in Rails support, as per [this](https://github.com/SchemaPlus/schema_plus_foreign_keys/issues/16#issuecomment-408518897) comment. It's not _quite_ as convenient as the `schema_plus_foreign_keys` support (ie it's not automatic) but it's not too onerous to provide the required option on the DSL methods.

**Comment by garyfoster** [comment]
Ya, I moved on too. the active_record_doctor gem has been helpful to identify missing foreign keys so we are just using that and will check our projects periodically with that tool.

**Comment by urkle** [comment]
I am now actively working on refreshing all of the SchemaPlus gems so they support Rails 5.2. (as I am going through the process of upgrading 5 rails apps that make use of these gems).   So expect to see new gem releases in the next week or so.

**Comment by urkle** [comment]
I'm closing this issue now as updates are flowing again.  New version of Schema+ Foreign Keys was just released.
